import { describe, expect, it } from "vitest";
import { buildMockup, headlineFor, paletteFor, renderMockupHtml } from "./mockup";

describe("paletteFor", () => {
  it("selects a palette from the business category", () => {
    expect(paletteFor("Italian restaurant")).not.toEqual(paletteFor("Dental clinic"));
    expect(paletteFor("Plumber")).toEqual(paletteFor("Roofing contractor"));
  });

  it("falls back to a neutral palette for an unknown category", () => {
    expect(paletteFor(undefined).bg).toBeTruthy();
    expect(paletteFor("something unusual").bg).toBeTruthy();
  });
});

describe("headlineFor", () => {
  it("writes category-appropriate copy without asserting facts about the business", () => {
    const headline = headlineFor("Rosa's Kitchenette", "restaurant", "Austin");
    expect(headline).toMatch(/Austin/);
    expect(headline).not.toMatch(/best|award|cheapest|number one/i);
  });
});

describe("renderMockupHtml", () => {
  it("labels itself a concept so it can never be mistaken for a live site", () => {
    const html = renderMockupHtml({ name: "Cedar & Loom" });
    expect(html).toMatch(/Concept preview generated by Finder/i);
    expect(html).toMatch(/not a live website/i);
  });

  it("escapes the business name and omits fields that were not supplied", () => {
    const html = renderMockupHtml({ name: '<img src=x onerror="alert(1)">' });
    expect(html).not.toContain('onerror="alert(1)"');
    expect(html).toContain("&lt;img");
    expect(html).not.toContain("<b>Call</b>");
  });

  it("includes public detail rows only when the data exists", () => {
    const html = renderMockupHtml({ name: "Cedar", phone: "+1 512 555 0138", address: "South Congress" });
    expect(html).toContain("+1 512 555 0138");
    expect(html).toContain("South Congress");
  });
});

describe("buildMockup", () => {
  it("returns the concept with a note about how it should be used", () => {
    const built = buildMockup({ name: "Cedar & Loom", category: "home goods", city: "Austin" });
    expect(built.note).toMatch(/public listing data only/i);
    expect(built.html.length).toBeGreaterThan(500);
  });
});
